sudo: required
services:
  - docker
before_install:
  - docker build -t bhavyacodes/react-test -f ./client/Dockerfile.dev ./client

script:
  # if any scripts exists with a status code other than zero, then travis assumes our build failed
  - docker run -e CI=true bhavyacodes/react-test npm test

after_success:
  - docker build -t bhavyacodes/multi-client ./client
  - docker build -t bhavyacodes/multi-nginx ./nginx
  - docker build -t bhavyacodes/multi-server ./server
  - docker build -t bhavyacodes/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bhavyacodes/multi-client
  - docker push bhavyacodes/multi-nginx
  - docker push bhavyacodes/multi-server
  - docker push bhavyacodes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-343867524622"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
