sudo: required
services:
  - docker
before_install:
  - docker build -t bhavyacodes/react-test -f ./client/Dockerfile.dev ./client

script:
  # if any scripts exists with a status code other than zero, then travis assumes our build failed
  - docker run -e CI=true bhavyacodes/react-test npm test

after_success:
  - docker build -t bhavyacodes/multi-client -f ./client
  - docker build -t bhavyacodes/multi-nginx -f ./nginx
  - docker build -t bhavyacodes/multi-server -f ./server
  - docker build -t bhavyacodes/multi-worker -f ./worker
